Create Table [dbo].[User] (
	"USERNAME" VARCHAR(20),
	"PASSWORD" VARCHAR(20)  NOT NULL,
	"EMAIL" VARCHAR(20) NOT NULL,
	"NAME" VARCHAR(60) NOT NULL,
	"CITY" VARCHAR(20),
	"PHONE" varchar(10),
	CONSTRAINT "PK_USER_UN" PRIMARY KEY ("USERNAME")
)