package pojos;

public enum Category {
	FICTION, NONFICTION, SCIFI, FANTACY, PHILOSOPHY, BIOGRAPHY, CLASSIC, HISTORICAL, HORROR, ROMANCE, HISTORY, THRILLER,
	SUSPENSE, AUTOBIOGRAPHY, POETRY, SELFHELP, CRIME, MYTHOLOGY;
}
